/**
 * Single source of truth for every domain enum used by the backend.
 *
 * Most enums are generated by Prisma from `schema.prisma` — we re-export them
 * here so application code never imports from `@prisma/client` directly. The
 * only enum defined manually is `Permission`, since permissions are stored as
 * free-form strings in the `permissions` table (so they can be edited at
 * runtime by an admin without a migration).
 */
export {
  Role,
  IncidentStatus,
  GithubEventType,
  NotificationChannel,
  NotificationEvent,
  AgentRole,
  // `LlmProviderKind` is the strategy enum (GEMINI/OPENAI/ANTHROPIC) — picks
  // which `LlmStrategy` class to instantiate. The `LlmProvider` MODEL is now
  // a configurable record in the DB, NOT the same as this enum.
  LlmProviderKind,
  IncidentLinkStatus,
  AuditAction,
  AuditActorType,
  ChatMessageRole,
  IndexingState,
} from '@prisma/client';

export * from './permission.enum';
